"""empty message

Revision ID: 6ac52e42d715
Revises: fb3c4096d450
Create Date: 2024-11-17 09:27:42.975468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac52e42d715'
down_revision = 'fb3c4096d450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('descriptors', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.drop_column('descriptors')
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###
