"""empty message

Revision ID: ae5fbdd2511f
Revises: 5bad9e5caad2
Create Date: 2024-11-21 15:47:52.195189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae5fbdd2511f'
down_revision = '5bad9e5caad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billboard', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('artists', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('total_tracks', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('album_type', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=False))
        batch_op.create_index(batch_op.f('ix_albums_billboard'), ['billboard'], unique=False)
        batch_op.drop_column('descriptors')
        batch_op.drop_column('release_date')
        batch_op.drop_column('cover_art')
        batch_op.drop_column('ranking')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('albums', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ranking', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('cover_art', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('release_date', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('descriptors', sa.TEXT(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_albums_billboard'))
        batch_op.drop_column('image_url')
        batch_op.drop_column('album_type')
        batch_op.drop_column('total_tracks')
        batch_op.drop_column('artists')
        batch_op.drop_column('billboard')

    # ### end Alembic commands ###
